#!/usr/bin/env python3
"""Generate the Flint traffic seed migration from real MDOT 2024 AADT data.

Source: MDOT's `MdotAadtCaadtCurrentYear` layer (Annual Average Daily Traffic),
extracted to WGS84 GeoJSON with GDAL:

    ogr2ogr -f GeoJSON data/flint_aadt_2024.geojson <gdb> MdotAadtCaadtCurrentYear \\
        -t_srs EPSG:4326 -spat -84.05 42.80 -83.40 43.25 -spat_srs EPSG:4326 \\
        -explodecollections -nlt LINESTRING \\
        -select PR,Aadt,AadtCommercial,FacilityType,Year,LocationId

This maps each AADT segment into the `traffic_segments` schema (migration 0019):
AADT (daily) -> a peak-hour volume reference the resolver modulates by the
time-of-day curve; road class (inferred from AADT magnitude) -> free-flow speed
and capacity -> a congestion ratio. Provenance is honest: this is MEASURED
historic average traffic, NOT a live feed (estimate_basis HOURLY_PATTERN).

Output: a SQL migration that DELETEs the placeholder corridors and seeds the
top-N Flint segments by AADT for the `flint` tenant. The full network is loaded
separately (it powers isochrones + the demand model); the resolver animates the
busiest roads, which is what the flow overlay can legibly carry.

Usage: python3 scripts/build_flint_aadt_migration.py [geojson] [top_n] > migrations/0020_flint_aadt_segments.sql
"""

import json
import sys

PEAK_HOUR_FACTOR = 0.095  # ~9.5% of AADT in the peak hour (urban K-factor)


def road_class(aadt: int):
    """(free_flow_mph, capacity_veh_per_hour) inferred from AADT magnitude,
    which proxies functional class better than the source FacilityType field
    here (the highest-AADT Flint segments are all class 2)."""
    if aadt >= 40000:
        return 65.0, 4200.0  # freeway-tier (I-69 / I-475 / US-23 corridors)
    if aadt >= 15000:
        return 50.0, 2400.0  # major arterial
    if aadt >= 6000:
        return 42.0, 1700.0  # arterial
    if aadt >= 2000:
        return 35.0, 1100.0  # collector
    return 30.0, 800.0       # local


def clamp(x, lo, hi):
    return max(lo, min(hi, x))


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main():
    geojson = sys.argv[1] if len(sys.argv) > 1 else "data/flint_aadt_2024.geojson"
    top_n = int(sys.argv[2]) if len(sys.argv) > 2 else 60

    features = [
        f for f in json.load(open(geojson))["features"]
        if f.get("geometry") and (f["properties"].get("Aadt") or 0) > 0
        and f["geometry"].get("type") == "LineString"
        and len(f["geometry"].get("coordinates", [])) >= 2
    ]
    features.sort(key=lambda f: f["properties"]["Aadt"], reverse=True)
    chosen = features[:top_n]

    rows = []
    for i, f in enumerate(chosen):
        p = f["properties"]
        aadt = int(p["Aadt"])
        pr = str(p.get("PR") or "unknown")
        free_flow, capacity = road_class(aadt)
        peak_hourly = round(aadt * PEAK_HOUR_FACTOR, 1)
        congestion = round(clamp(peak_hourly / capacity, 0.0, 0.95), 3)
        base_speed = round(free_flow * (1.0 - 0.45 * congestion), 1)
        geom = json.dumps(f["geometry"], separators=(",", ":"))
        segment_key = f"aadt:flint:{pr}:{i}"
        corridor = f"MDOT route {pr}"
        direction = f"AADT segment (class {p.get('FacilityType', '?')})"
        support = (
            f"MDOT 2024 Annual Average Daily Traffic: {aadt:,} vehicles/day on "
            f"route {pr}. Hourly flow inferred from the AADT via a time-of-day "
            f"curve. This is measured historic average traffic, not a live feed."
        )
        rows.append(
            "    (" + ", ".join([
                sql_str(segment_key), sql_str(corridor), sql_str(direction),
                "ST_GeomFromGeoJSON(" + sql_str(geom) + ")::geography",
                "'hourly_pattern'", "'fixture'",
                sql_str("MDOT 2024 AADT (measured historic average)"),
                sql_str(support),
                f"{free_flow}::double precision", f"{base_speed}::double precision",
                f"{peak_hourly}::double precision", "0.7::double precision",
            ]) + ")"
        )

    cols = (
        "geometry, " * 0 +  # placeholder for readability
        "segment_key, corridor_name, direction_label, geometry, estimate_basis, "
        "source_status, source_label, support_note, free_flow_speed_mph, "
        "base_speed_mph, base_volume_per_hour, confidence"
    )

    print("-- Real Flint traffic seed from MDOT 2024 AADT (MdotAadtCaadtCurrentYear).")
    print("-- Generated by scripts/build_flint_aadt_migration.py from")
    print("-- data/flint_aadt_2024.geojson. Replaces the 6 placeholder corridors")
    print(f"-- (0019) with the top {len(chosen)} Flint segments by real AADT volume.")
    print("-- Provenance is honest: measured historic average (HOURLY_PATTERN), not live.")
    print()
    print("DELETE FROM traffic_segments")
    print("WHERE network_id = 'flint-downtown' AND segment_key LIKE 'traffic:flint:%';")
    print()
    print("INSERT INTO traffic_segments (")
    print("    tenant_id, network_id, " + cols)
    print(")")
    print("SELECT")
    print("    t.id, 'flint-downtown', v.segment_key, v.corridor_name, v.direction_label,")
    print("    v.geometry, v.estimate_basis, v.source_status, v.source_label, v.support_note,")
    print("    v.free_flow_speed_mph, v.base_speed_mph, v.base_volume_per_hour, v.confidence")
    print("FROM tenants t")
    print("CROSS JOIN (")
    print("    VALUES")
    print(",\n".join(rows))
    print(") AS v(")
    print("    segment_key, corridor_name, direction_label, geometry, estimate_basis,")
    print("    source_status, source_label, support_note, free_flow_speed_mph,")
    print("    base_speed_mph, base_volume_per_hour, confidence")
    print(")")
    print("WHERE t.slug = 'flint'")
    print("ON CONFLICT (tenant_id, network_id, segment_key) DO NOTHING;")


if __name__ == "__main__":
    main()
